
-- ATTENDANCE 考勤

DESC CAM_ATTENDANCE;

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE STAFFNAME = "林立" AND CHECK_TYPE = "CHECK_IN";

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE CHECK_TIME IS NOT NULL ORDER BY CHECK_TIME DESC; 

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE DATE_FORMAT(T.CHECK_TIME, '%Y-%m-%d') = '2018-11-27'; 

SELECT DATE_FORMAT(T.CHECK_TIME,'%Y-%m-%d') FROM PINSTANCE.CAM_ATTENDANCE T;
-- 昨天的记录
SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE TO_DAYS(NOW()) -  TO_DAYS(T.CALCULATETIME) <= 1 ORDER BY CALCULATETIME DESC;

DELETE FROM PINSTANCE.CAM_ATTENDANCE WHERE TO_DAYS(NOW()) -  TO_DAYS(CALCULATETIME) <= 1 ORDER BY CALCULATETIME DESC LIMIT 1;

DELETE  FROM PINSTANCE.CAM_ATTENDANCE WHERE CALCULATETIME > NOW();

SELECT CURDATE();

SELECT DATE_FORMAT(NOW(),'%Y-%m-%d');

SELECT MIN(WORK_DATE) FROM PINSTANCE.CAM_ATTENDANCE;

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE_HIS T ORDER BY CHECK_TIME;

SELECT 
    A.*
FROM
    PINSTANCE.CAM_ATTENDANCE_HIS A
        LEFT JOIN
    CAM_TENANT T ON A.TENANT = T.RECID
        LEFT JOIN
    CAM_STAFF S ON S.RECID = A.STAFF
WHERE
    DATE_FORMAT(WORK_DATE, '%Y-%m-%d') = '2017-11-30'
        AND T.NAME = '孙建卫'
        AND S.NAME = '林立'
ORDER BY A.WORK_DATE DESC;

-- CHECK RECORD 打卡

DESC PINSTANCE.CAM_CHECK;

SELECT T.* FROM PINSTANCE.CAM_CHECK T ORDER BY CHECK_TIME DESC LIMIT 1;

DELETE  FROM PINSTANCE.CAM_CHECK ORDER BY CHECK_TIME DESC LIMIT 1;

-- 租户 

DESC CAM_TENANT;

SELECT T.* FROM CAM_TENANT T WHERE NAME = "孙卫建";

-- 员工

DESC CAM_STAFF;

SELECT T.* FROM CAM_STAFF T WHERE NAME = '林立';

-- 单据定义

DESC INSTANCE.CAM_CUSTOMFORM_DEFINITION;



