
-- ATTENDANCE 考勤

DESC CAM_ATTENDANCE;

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE STAFFNAME = "林立" AND CHECK_TYPE = "CHECK_IN";

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE CHECK_TIME IS NOT NULL ORDER BY CHECK_TIME DESC; 

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE DATE_FORMAT(T.CHECK_TIME, '%Y-%m-%d') = '2018-11-27'; 

SELECT DATE_FORMAT(T.CHECK_TIME,'%Y-%m-%d') FROM PINSTANCE.CAM_ATTENDANCE T;
-- 昨天的记录
SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE T WHERE TO_DAYS(NOW()) -  TO_DAYS(T.CALCULATETIME) <= 1 AND STAFFNAME = '林俊存' ORDER BY CALCULATETIME DESC;

DELETE FROM PINSTANCE.CAM_ATTENDANCE WHERE TO_DAYS(NOW()) -  TO_DAYS(CALCULATETIME) <= 1 AND STAFFNAME = '林立' ORDER BY CALCULATETIME DESC LIMIT 1;

DELETE  FROM PINSTANCE.CAM_ATTENDANCE WHERE CALCULATETIME > NOW();

SELECT CURDATE();

SELECT TO_DAYS(NOW());

SELECT DATE_FORMAT(NOW(),'%Y-%m-%d');

SELECT MIN(WORK_DATE) FROM PINSTANCE.CAM_ATTENDANCE;

SELECT T.* FROM PINSTANCE.CAM_ATTENDANCE_HIS T ORDER BY CHECK_TIME;

SELECT 
    A.*
FROM
    PINSTANCE.CAM_ATTENDANCE_HIS A
        LEFT JOIN
    CAM_TENANT T ON A.TENANT = T.RECID
        LEFT JOIN
    CAM_STAFF S ON S.RECID = A.STAFF
WHERE
    DATE_FORMAT(WORK_DATE, '%Y-%m-%d') = '2017-11-30'
        AND T.NAME = '孙建卫'
        AND S.NAME = '林立'
ORDER BY A.WORK_DATE DESC;

-- CHECK RECORD 打卡

DESC PINSTANCE.CAM_CHECK;

SELECT T.* FROM PINSTANCE.CAM_CHECK T ORDER BY CHECK_TIME DESC LIMIT 1;

DELETE  FROM PINSTANCE.CAM_CHECK ORDER BY CHECK_TIME DESC LIMIT 1;

-- 租户 

DESC CAM_TENANT;


SELECT HEX(T.RECID),T.* FROM PINSTANCE.CAM_TENANT T WHERE T.NAME LIKE '北京久其%';

-- 员工

DESC CAM_STAFF;

SELECT S.NAME,S.EMAIL FROM CAM_STAFF S LEFT JOIN CAM_TENANT T ON T.RECID = S.TENANT WHERE T.NAME LIKE '北京久其%' GROUP BY S.EMAIL HAVING COUNT(S.EMAIL) = 2;

SELECT * FROM CAM_STAFF S WHERE S.EMAIL = 'hongxuemin@jiuqi.com.cn';

SELECT COUNT(*) FROM CAM_STAFF S LEFT JOIN CAM_TENANT T ON T.RECID = S.TENANT  WHERE S.EMAIL IS NULL AND T.NAME LIKE '北京久其%';

-- 单据定义

DESC INSTANCE.CAM_CUSTOMFORM_DEFINITION;


-- 常用功能

DESC PINSTANCE.CAM_COMMONFUNCTION;

SELECT * FROM INST_JKS.CAM_COMMONFUNCTION ;

SELECT * FROM INST_JKS.CAM_COMMONFUNCTION_BD;
-- 复制表(备份)
CREATE TABLE INST_JKS.CAM_COMMONFUNCTION_BD SELECT * FROM INST_JKS.CAM_COMMONFUNCTION;

UPDATE CAM_COMMONFUNCTION  SET FUNCTIONTYPE = 0;
-- 复制列
UPDATE CAM_COMMONFUNCTION SET FUNCTIONID = UNUSED_FUNCTIONID;

-- 音视频会议
USE MASTER;

DESC CAM_ZOOMUSER;

DELETE FROM CAM_ZOOMUSER;

SELECT * FROM CAM_ZOOMUSER;

UPDATE CAM_ZOOMUSER SET MARK = 1;

ALTER TABLE CAM_ZOOMUSER DROP COLUMN TOKEN ,DROP COLUMN TENANTID;

SELECT HEX(Z.CREATOR) ,Z.EMAIL,S.NAME FROM MASTER.CAM_ZOOMUSER Z LEFT JOIN INSTANCE.CAM_STAFF S ON S.RECID = Z.CREATOR WHERE Z.CREATOR IS NOT NULL ;

DELETE FROM CAM_ZOOMUSER  WHERE CREATOR = 0x648C76968EF6F660018B6A791C26173D;  

SELECT HEX(T.RECID),T.* FROM CAM_AVMEETINGINFO T;

DELETE FROM CAM_AVMEETINGINFO;

UPDATE CAM_AVMEETINGINFO SET STATUS = 2;

SELECT * FROM CAM_AVMEETINGCUSTOMCONFIG;



-- Z0zDUnx1SvCZnZXJyWejxA 

-- cZUUougJnFMSzpzW1pQT7Cfki7f5rWMZsjxk 


-- 会议
USE PINSTANCE;
SELECT HEX(RECID),M.* FROM CAM_MEETING M ; -- WHERE RECID = 0x68EA929B80000041299E766E5229EC45;

UPDATE CAM_MEETING SET AUDITSTATUS = 0 WHERE RECID = 0x6855FA8820000021387D359EBAAC17BF;

-- 回复
SELECT HEX(RECID),HEX(SENDER),HEX(RECV),MR.* FROM CAM_MEETREPLY MR ;-- WHERE MEETID = 0x68EA929B80000041299E766E5229EC45;
DELETE FROM CAM_MEETREPLY WHERE PARENTID IS NOT NULL AND RECV IS NULL;
ALTER TABLE CAM_MEETREPLY DROP COLUMN ROOTID;

-- 成员
SELECT * FROM CAM_MEETMEMBER WHERE MEETID = 0x68EA929B80000041299E766E5229EC45;









