-- 消费记录

SELECT COUNT FROM sms_01.SSC_CONSUME_RECORD;
    
SELECT 
	C.RECID,T.RECID,HEX(TENANT),T.NAME, C.CREATETIME, SUM(COUNT), SUM(AMOUNT)
FROM
	sms_01.SSC_CONSUME_RECORD AS C LEFT JOIN  sms_01.SSC_TENANT T ON T.RECID = C.TENANT
GROUP BY CREATETIME , TENANT
ORDER BY CREATETIME DESC;

-- 租户

SELECT * FROM sms_01.SSC_TENANT;
    